---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:  
    developerConfiguration:
      featureGates: 
        - LiveMigration
        - NetworkBindingPlugins
        - Snapshot
    ksmConfiguration:
      nodeLabelSelector: {}
    smbios:
      sku: "TalosCloud"
      version: "v0.1.0"
      manufacturer: "Talos Virtualization"
      product: "talosvm"
      family: "ccio"
